### ISSUE TITLE
Remove script tag from ignition/app/views/layouts/_navbar.html.erb

### ISSUE THREAD

**Issue by beatriceo** [beatriceo/ignition#26]
Need to figure out how to link the `places.js` file in the `javascript/packs` folder and remove the `<script>` tag from the `.erb` file.

**Comment by Paoda** [comment]
![image](https://user-images.githubusercontent.com/22038970/44497499-a6843e80-a671-11e8-835f-ffa2ec10b001.png)

Not quite up to date; On 3be032011fa59f5773afbd561bd28f28a64e7240, however this error relating to what you're talking about appears. 

The server still renders the page fine, and the AJAX in the navbar also works. Which doesn't make it _that_ big of a deal. Nevertheless, hopefully this enhancement will address this error.

**Comment by paoda** [comment]
Closed due to inactivity.
